In [1]:
import xgboost

In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
df=pd.read_csv("https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-red.csv",sep = ';')

In [18]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [19]:
df.duplicated().sum()

240

In [20]:
df = df.drop_duplicates()

In [21]:
df.duplicated().sum()

0

In [22]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1359.000000       1359.000000  1359.000000     1359.000000   
mean        8.310596          0.529478     0.272333        2.523400   
std         1.736990          0.183031     0.195537        1.352314   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.430000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1359.000000          1359.000000           1359.000000  1359.000000   
mean      0.088124            15.893304             46.825975     0.996709   
std       0.049377            10.447270             33.408946     0.001869   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996700   
75%       0.091000            21.000000             63.000000     0.997820   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1359.000000  1359.000000  1359.000000  1359.000000  
mean      3.309787     0.658705    10.432315     5.623252  
std       0.155036     0.170667     1.082065     0.823578  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [24]:
x = df.drop('quality',axis=1)

In [26]:
y=df['quality']

In [28]:
from sklearn.model_selection import train_test_split,GridSearchCV

In [29]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=10)

In [32]:
from sklearn.ensemble import GradientBoostingClassifier
classifier=GradientBoostingClassifier()

In [34]:
parameters = {
    'loss':['logloss','deviance','exponential'],
    'learning_rate':[0.1,0.01,0.02,0.2],
    'n_estimators':[100,200,300,400],
    'criterion':['friedman_mse','squared_error']
    
}

In [36]:
GridSearchCV(estimator=classifier,param_grid=parameters,scoring='accuracy',cv=5,verbose=3)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.1, 0.01, 0.02, 0.2],
                         'loss': ['logloss', 'deviance', 'exponential'],
                         'n_estimators': [100, 200, 300, 400]},
             scoring='accuracy', verbose=3)

In [37]:
cv.fit(X_train,y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits
[CV 1/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=100;, score=nan total time=   0.0s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=100;, score=nan total time=   0.0s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=100;, score=nan total time=   0.0s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=100;, score=nan total time=   0.0s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=100;, score=nan total time=   0.0s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=200;, score=nan total time=   0.0s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=200;, score=nan total time=   0.0s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.1, loss=logloss, n_estimators=200;, score=nan total time=  

[CV 1/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.615 total time=   1.2s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.571 total time=   1.3s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.621 total time=   1.2s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.582 total time=   1.3s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.582 total time=   1.4s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=200;, score=0.577 total time=   2.6s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=200;, score=0.571 total time=   2.4s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.01, loss=deviance, n_estimators=200;, score=0.621 total time=   2.3s
[CV 4/5] END criterion=f

[CV 4/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=200;, score=0.604 total time=   2.8s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=200;, score=0.593 total time=   2.5s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.560 total time=   3.8s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.544 total time=   3.8s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.593 total time=   3.9s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.571 total time=   4.0s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.588 total time=   4.0s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.02, loss=deviance, n_estimators=400;, score=0.538 total time=   5.4s
[CV 2/5] END criterion=f

[CV 2/5] END criterion=friedman_mse, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.495 total time=   4.6s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.610 total time=   4.7s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.593 total time=   4.6s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.522 total time=   4.5s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 5/5] END criterion=fried

[CV 1/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.615 total time=   1.3s
[CV 2/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.571 total time=   1.3s
[CV 3/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.621 total time=   1.3s
[CV 4/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.582 total time=   1.2s
[CV 5/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=100;, score=0.582 total time=   1.2s
[CV 1/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=200;, score=0.577 total time=   2.2s
[CV 2/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=200;, score=0.571 total time=   2.2s
[CV 3/5] END criterion=squared_error, learning_rate=0.01, loss=deviance, n_estimators=200;, score=0.626 total time=   2.3s
[CV 4/5] END cri

[CV 3/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=200;, score=0.621 total time=   2.3s
[CV 4/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=200;, score=0.599 total time=   2.5s
[CV 5/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=200;, score=0.593 total time=   2.5s
[CV 1/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.555 total time=   3.8s
[CV 2/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.544 total time=   3.6s
[CV 3/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.599 total time=   3.8s
[CV 4/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.571 total time=   3.7s
[CV 5/5] END criterion=squared_error, learning_rate=0.02, loss=deviance, n_estimators=300;, score=0.588 total time=   3.7s
[CV 1/5] END cri

[CV 1/5] END criterion=squared_error, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.500 total time=   5.0s
[CV 2/5] END criterion=squared_error, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.500 total time=   4.3s
[CV 3/5] END criterion=squared_error, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.599 total time=   4.2s
[CV 4/5] END criterion=squared_error, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.593 total time=   4.3s
[CV 5/5] END criterion=squared_error, learning_rate=0.2, loss=deviance, n_estimators=400;, score=0.516 total time=   4.3s
[CV 1/5] END criterion=squared_error, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 2/5] END criterion=squared_error, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 3/5] END criterion=squared_error, learning_rate=0.2, loss=exponential, n_estimators=100;, score=nan total time=   0.0s
[CV 4/5] END criterio

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.1, 0.01, 0.02, 0.2],
                         'loss': ['logloss', 'deviance', 'exponential'],
                         'n_estimators': [100, 200, 300, 400]},
             scoring='accuracy', verbose=3)

In [38]:
cv.best_params_

{'criterion': 'friedman_mse',
 'learning_rate': 0.02,
 'loss': 'deviance',
 'n_estimators': 100}

In [39]:
classifier = GradientBoostingClassifier(criterion = 'friedman_mse',learning_rate=0.02,loss='deviance',n_estimators=100)

In [40]:
classifier.fit(X_train,y_train)

GradientBoostingClassifier(learning_rate=0.02)

In [42]:
y_predict = classifier.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [46]:
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.5857461024498887
[[  0   0   3   0   0   0]
 [  0   0  17   4   1   0]
 [  1   1 133  52   0   1]
 [  0   1  56 110   9   0]
 [  0   0   3  30  20   0]
 [  0   0   0   4   3   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        22
           5       0.63      0.71      0.67       188
           6       0.55      0.62      0.59       176
           7       0.61      0.38      0.47        53
           8       0.00      0.00      0.00         7

    accuracy                           0.59       449
   macro avg       0.30      0.28      0.29       449
weighted avg       0.55      0.59      0.56       449

